# Generated by Django 5.2.11 on 2026-02-19 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiracyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('last_incident', models.DateTimeField(blank=True, null=True)),
                ('incidents_count', models.IntegerField(default=0)),
                ('recommended_speed', models.IntegerField(blank=True, null=True)),
                ('armed_escort_recommended', models.BooleanField(default=False)),
                ('report_to_ukmto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('storm', 'Storm'), ('hurricane', 'Hurricane'), ('extreme_wind', 'Extreme Wind'), ('heavy_rain', 'Heavy Rain'), ('fog', 'Fog'), ('high_waves', 'High Waves'), ('tsunami', 'Tsunami')], max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('alert', 'Alert'), ('emergency', 'Emergency')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_name', models.CharField(max_length=255)),
                ('affected_radius_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('wave_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('visibility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('issued_time', models.DateTimeField()),
                ('expires_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_name', models.CharField(max_length=255)),
                ('accident_type', models.CharField(choices=[('collision', 'Collision'), ('grounding', 'Grounding'), ('fire', 'Fire'), ('explosion', 'Explosion'), ('flooding', 'Flooding'), ('machinery_failure', 'Machinery Failure'), ('other', 'Other')], max_length=50)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('casualties', models.IntegerField(default=0)),
                ('total_loss', models.BooleanField(default=False)),
                ('estimated_damage_usd', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessels', models.ManyToManyField(related_name='accident_histories', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('collision', 'Collision'), ('grounding', 'Grounding'), ('fire', 'Fire'), ('explosion', 'Explosion'), ('flooding', 'Flooding'), ('machinery_failure', 'Machinery Failure'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel_involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_events', to='vessels.vessel')),
            ],
            options={
                'indexes': [models.Index(fields=['event_time'], name='safety_safe_event_t_39a567_idx')],
            },
        ),
    ]
