# Generated by Django 5.2.11 on 2026-02-19 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unlocode', models.CharField(help_text='UN/LOCODE', max_length=5, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('port_type', models.CharField(choices=[('container', 'Container Port'), ('bulk_cargo', 'Bulk Cargo'), ('general_cargo', 'General Cargo'), ('oil_lng', 'Oil/LNG'), ('multipurpose', 'Multipurpose')], default='multipurpose', max_length=50)),
                ('number_of_berths', models.IntegerField(default=0)),
                ('average_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('annual_container_capacity', models.IntegerField(blank=True, help_text='TEU', null=True)),
                ('annual_cargo_capacity', models.IntegerField(blank=True, help_text='Tons', null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('berth_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_loaded', models.DecimalField(decimal_places=2, default=0, help_text='Tons', max_digits=10)),
                ('cargo_unloaded', models.DecimalField(decimal_places=2, default=0, help_text='Tons', max_digits=10)),
                ('turnaround_time', models.DecimalField(blank=True, decimal_places=2, help_text='Hours', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_calls', to='vessels.vessel')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_movements', to='ports.port')),
            ],
        ),
        migrations.CreateModel(
            name='PortStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_arrivals', models.IntegerField(default=0)),
                ('total_departures', models.IntegerField(default=0)),
                ('current_vessels', models.IntegerField(default=0)),
                ('average_wait_time', models.DecimalField(decimal_places=2, default=0, help_text='Hours', max_digits=6)),
                ('average_berth_time', models.DecimalField(decimal_places=2, default=0, help_text='Hours', max_digits=6)),
                ('occupied_berths', models.IntegerField(default=0)),
                ('free_berths', models.IntegerField(default=0)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='ports.port')),
            ],
        ),
        migrations.CreateModel(
            name='CongestionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congestion_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('queue_length', models.IntegerField(default=0)),
                ('estimated_wait_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('berths_available', models.IntegerField(default=0)),
                ('berths_occupied', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congestion_history', to='ports.port')),
            ],
            options={
                'indexes': [models.Index(fields=['port', '-timestamp'], name='ports_conge_port_id_af3f96_idx')],
            },
        ),
    ]
