# Generated by Django 5.2.11 on 2026-02-19 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.IntegerField(help_text='International Maritime Organization number', unique=True)),
                ('mmsi', models.BigIntegerField(help_text='Maritime Mobile Service Identity', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(choices=[('container', 'Container Ship'), ('tanker', 'Tanker'), ('bulk', 'Bulk Carrier'), ('fishing', 'Fishing Vessel'), ('passenger', 'Passenger Ship'), ('other', 'Other')], max_length=50)),
                ('flag', models.CharField(help_text='Country ISO code', max_length=3)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('in_port', 'In Port'), ('anchored', 'Anchored'), ('offline', 'Offline')], default='offline', max_length=50)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in meters', max_digits=8, null=True)),
                ('beam', models.DecimalField(blank=True, decimal_places=2, help_text='Width in meters', max_digits=8, null=True)),
                ('draft', models.DecimalField(blank=True, decimal_places=2, help_text='Depth in meters', max_digits=8, null=True)),
                ('last_position_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('last_position_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('last_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in knots', max_digits=5, null=True)),
                ('last_heading', models.DecimalField(blank=True, decimal_places=2, help_text='Heading in degrees', max_digits=5, null=True)),
                ('last_position_update', models.DateTimeField(blank=True, null=True)),
                ('external_api_source', models.CharField(blank=True, max_length=50, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VesselRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_port', models.CharField(max_length=255)),
                ('destination_port', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('expected_duration', models.DecimalField(blank=True, decimal_places=2, help_text='Duration in hours', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_route', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VesselAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('position_change', 'Position Change'), ('port_arrival', 'Port Arrival'), ('port_departure', 'Port Departure'), ('speed_change', 'Speed Change'), ('heading_change', 'Heading Change'), ('status_change', 'Status Change')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_alerts', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vessels.vessel')),
            ],
            options={
                'unique_together': {('vessel', 'user', 'alert_type')},
            },
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vessel', '-timestamp'], name='vessels_ves_vessel__2ffb7b_idx')],
            },
        ),
    ]
